import argparse
import traceback
import os
import sys

""" Generate final application (CSDF) model """

# example:
# python ./generate_final_app_model.py --cnn /home/svetlana/ONNX/OnnxZooModels/mnist.onnx -tg ./output/mnist/task_graph.json -p ./output/architecture/jetson.json -m ./output/mnist/mapping.json -o ./output/mnist/


def main():
    # import current directory and it's subdirectories into system path for the current console
    # this would allow to import project modules without adding the project to the PYTHONPATH
    this_dir = os.path.dirname(__file__)
    sys.path.append(this_dir)

    # import project modules
    from dnn_builders.input_dnn_manager import load_or_build_dnn_for_analysis
    from models.dnn_model.dnn import set_built_in
    from models.dnn_model.transformation.ops_fusion import fuse_built_in
    from models.dnn_model.transformation.external_ios_processor import data_layers_to_external_ios
    from converters.json_converters.json_to_architecture import json_to_architecture
    from converters.json_converters.json_task_graph import parse_task_graph_json
    from converters.json_converters.json_to_mapping import json_to_mapping
    from converters.json_converters.dnn_inf_model_to_json import dnn_inf_model_to_json
    from models.app_model.dnn_inf_model import generate_dnn_inference_model
    from DSE.scheduling.dnn_scheduling import DNNScheduling
    from util import print_stage

    # general arguments
    parser = argparse.ArgumentParser(description='The script generates mixed CPU (ARM-CL) +'
                                                 ' GPU (TensorRT) code for a cnn')

    parser.add_argument('--cnn', metavar='--cnn', type=str, action='store', required=True,
                        help='path to a CNN. Can be a path to: '
                             '1) a path to an .onnx file; '
                             '2) a path to .h5 file (cnn in format of Keras DL framework). '
                             '3) a path to .json file (cnn in internal format. This format'
                             'can be obtained from on .onnx or .h5 file using ./dnn_to_json script)')

    parser.add_argument('-fo', metavar='--fused-ops', type=str, action='store',
                        default='activation,normalization,arithmetic,skip',
                        help='List built-in (fused) operators within a cnn. A cnn layers, performing a built-in'
                             ' operator is fused with another layer also referred as a "parent" layer. For example'
                             ' an activation (e.g. ReLU) layer, following a convolutional layer,'
                             ' can be fused with the convolutional layer. In this case, the activation layer is'
                             ' the fused layer, and the convolutional layer is the "parent" layer.'
                             ' Fused layers are always mapped onto the same processor'
                             ' as their "parent" layer. Also, fused layers do not have an intermediate'
                             ' output date (output buffer) of their own.'
                             ' NOTE: LIST OF FUSED OPS SHOULD NOT CHANGE BETWEEN THE SUBSEQUENT SCRIPTS')

    parser.add_argument('-tg', metavar='--task-graph', type=str, action='store', required=True,
                        help='path to .json file with the task-graph (SDF) model generated '
                             'for the input cnn by the ./dnn_to_sdf_task_graph.py script')

    parser.add_argument('-p', metavar='--platform', type=str, action='store', required=True,
                        help='path to edge platform (architecture) description, saved in .json format')

    parser.add_argument('-m', metavar='--mapping', type=str, action='store', required=True,
                        help='path to mapping description, generated by ./generate_mapping.py script '
                             'and saved in .json format.')

    parser.add_argument('-s', metavar='--schedule', type=str, action='store', default="pipeline",
                        help='schedule type in [pipeline, sequential]')

    parser.add_argument('-o', metavar='--out-dir', type=str, action='store', default="./output",
                        help='path to output files directory')

    # general flags
    parser.add_argument("--silent", help="do not provide print-out for the script steps", action="store_true", default=False)

    args = parser.parse_args()
    try:
        # Extract parameters from command-line arguments"
        cnn_path = args.cnn
        task_graph_path = args.tg
        platform_path = args.p
        mapping_path = args.m
        output_dir = args.o
        fused_ops_spec = args.fo
        fused_ops = fused_ops_spec.split(',')

        schedule_str = args.s
        if schedule_str not in ["pipeline", "sequential"]:
            schedule_str = "pipeline"
            print("WARNING: unknown schedule", schedule_str, "! Default (pipeline) schedule is used instead.")
        schedule_type = DNNScheduling.PIPELINE if schedule_str == "pipeline" else DNNScheduling.SEQUENTIAL

        silent = args.silent
        verbose = not silent

        # read DNN
        stage = "Reading input DNN"
        print_stage(stage, verbose)
        dnn = load_or_build_dnn_for_analysis(cnn_path, verbose=verbose)
        # print DNN
        # dnn.print_details()

        # optimize dnn: fuse operators
        if len(fused_ops) > 0:
            stage = "Optimize DNN: fuse layers that perform operators " + str(fused_ops_spec)
            print_stage(stage, verbose)
            set_built_in(dnn, fused_ops)
            fuse_built_in(dnn)

        # optimize dnn: specify i/os explicitly
        stage = "Optimize DNN: transform I/O data layers into external Inputs/Outputs"
        print_stage(stage, verbose)
        data_layers_to_external_ios(dnn)

        stage = "Reading task graph (SDF) model "
        print_stage(stage, verbose)
        task_graph = parse_task_graph_json(task_graph_path)

        stage = "Reading target platform architecture"
        print_stage(stage, verbose)
        architecture = json_to_architecture(platform_path)

        stage = "Reading DNN mapping onto target edge platform"
        print_stage(stage, verbose)
        mapping = json_to_mapping(mapping_path, task_graph, architecture)
        # print(mapping)

        stage = "Generating final application (CSDF) model"
        print_stage(stage, verbose)
        app_model = generate_dnn_inference_model(dnn, architecture, task_graph, mapping, schedule_type)

        stage = "Saving final application model as .json"
        print_stage(stage, verbose)
        out_file_path = str(os.path.join(output_dir, "app.json"))
        dnn_inf_model_to_json(app_model, out_file_path)

    except Exception as e:
        print("Final Application (CSDF) model creation error: " + str(e))
        traceback.print_tb(e.__traceback__)


if __name__ == "__main__":
    main()